# Generated by Django 4.2.4 on 2023-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                    ("On Hold", "On Hold"),
                ],
                default="Active",
                max_length=10,
            ),
        ),
    ]
