# Generated by Django 4.2.4 on 2023-09-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsite',
            old_name='coordinates',
            new_name='coordinate',
        ),
    ]
